version: "3"

services:
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: administrator
      MINIO_ROOT_PASSWORD: administrator
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000" # service
      - "9001:9001" # web

  ssh-server:
    image: ssh-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
  
  postgres:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: postgres
      PGPASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      # POSTGRES_HOST_AUTH_METHOD: trust
    # psql -h localhost -p 5432 -U postgres -d postgres
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  # meilisearch:
  #   image: getmeili/meilisearch:latest
  #   ports:
  #     - 7700:7700
  #   environment:
  #     MEILI_MASTER_KEY: "masterKey"
  