# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import keyvalue_pb2 as keyvalue__pb2


class KeyValueStoreStub(object):
    """Interface for key-value store
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exists = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/Exists',
                request_serializer=keyvalue__pb2.GetBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.ExistsReply.FromString,
                )
        self.Delete = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/Delete',
                request_serializer=keyvalue__pb2.GetBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.ExistsReply.FromString,
                )
        self.PutBytes = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/PutBytes',
                request_serializer=keyvalue__pb2.PutBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.PutBytesReply.FromString,
                )
        self.GetBytes = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/GetBytes',
                request_serializer=keyvalue__pb2.GetBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.GetBytesReply.FromString,
                )
        self.PutBytesStream = channel.stream_unary(
                '/keyvaluestore.KeyValueStore/PutBytesStream',
                request_serializer=keyvalue__pb2.FileChunk.SerializeToString,
                response_deserializer=keyvalue__pb2.PutBytesReply.FromString,
                )
        self.GetBytesStream = channel.unary_stream(
                '/keyvaluestore.KeyValueStore/GetBytesStream',
                request_serializer=keyvalue__pb2.GetBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.FileChunk.FromString,
                )


class KeyValueStoreServicer(object):
    """Interface for key-value store
    """

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutBytesStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBytesStream(self, request, context):
        """トレーラーメタデータを使い、ストリームの最後にメタデータを送信することが可能
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=keyvalue__pb2.GetBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.ExistsReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=keyvalue__pb2.GetBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.ExistsReply.SerializeToString,
            ),
            'PutBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.PutBytes,
                    request_deserializer=keyvalue__pb2.PutBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.PutBytesReply.SerializeToString,
            ),
            'GetBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBytes,
                    request_deserializer=keyvalue__pb2.GetBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.GetBytesReply.SerializeToString,
            ),
            'PutBytesStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PutBytesStream,
                    request_deserializer=keyvalue__pb2.FileChunk.FromString,
                    response_serializer=keyvalue__pb2.PutBytesReply.SerializeToString,
            ),
            'GetBytesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBytesStream,
                    request_deserializer=keyvalue__pb2.GetBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyvaluestore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Interface for key-value store
    """

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/Exists',
            keyvalue__pb2.GetBytesRequest.SerializeToString,
            keyvalue__pb2.ExistsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/Delete',
            keyvalue__pb2.GetBytesRequest.SerializeToString,
            keyvalue__pb2.ExistsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/PutBytes',
            keyvalue__pb2.PutBytesRequest.SerializeToString,
            keyvalue__pb2.PutBytesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/GetBytes',
            keyvalue__pb2.GetBytesRequest.SerializeToString,
            keyvalue__pb2.GetBytesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutBytesStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/keyvaluestore.KeyValueStore/PutBytesStream',
            keyvalue__pb2.FileChunk.SerializeToString,
            keyvalue__pb2.PutBytesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBytesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/keyvaluestore.KeyValueStore/GetBytesStream',
            keyvalue__pb2.GetBytesRequest.SerializeToString,
            keyvalue__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
