# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import keyvalue_pb2 as keyvalue__pb2


class KeyValueStoreStub(object):
    """Interface for key-value store
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteBytes = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/WriteBytes',
                request_serializer=keyvalue__pb2.WriteBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.WriteBytesReply.FromString,
                )
        self.ReadBytes = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/ReadBytes',
                request_serializer=keyvalue__pb2.ReadBytesRequest.SerializeToString,
                response_deserializer=keyvalue__pb2.ReadBytesReply.FromString,
                )


class KeyValueStoreServicer(object):
    """Interface for key-value store
    """

    def WriteBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteBytes,
                    request_deserializer=keyvalue__pb2.WriteBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.WriteBytesReply.SerializeToString,
            ),
            'ReadBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBytes,
                    request_deserializer=keyvalue__pb2.ReadBytesRequest.FromString,
                    response_serializer=keyvalue__pb2.ReadBytesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyvaluestore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Interface for key-value store
    """

    @staticmethod
    def WriteBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/WriteBytes',
            keyvalue__pb2.WriteBytesRequest.SerializeToString,
            keyvalue__pb2.WriteBytesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/ReadBytes',
            keyvalue__pb2.ReadBytesRequest.SerializeToString,
            keyvalue__pb2.ReadBytesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
