# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyvalue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekeyvalue.proto\x12\rkeyvaluestore\"/\n\x11WriteBytesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1e\n\x0fWriteBytesReply\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1f\n\x10ReadBytesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1f\n\x0eReadBytesReply\x12\r\n\x05value\x18\x01 \x01(\x0c\x32\xb0\x01\n\rKeyValueStore\x12P\n\nWriteBytes\x12 .keyvaluestore.WriteBytesRequest\x1a\x1e.keyvaluestore.WriteBytesReply\"\x00\x12M\n\tReadBytes\x12\x1f.keyvaluestore.ReadBytesRequest\x1a\x1d.keyvaluestore.ReadBytesReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyvalue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WRITEBYTESREQUEST']._serialized_start=33
  _globals['_WRITEBYTESREQUEST']._serialized_end=80
  _globals['_WRITEBYTESREPLY']._serialized_start=82
  _globals['_WRITEBYTESREPLY']._serialized_end=112
  _globals['_READBYTESREQUEST']._serialized_start=114
  _globals['_READBYTESREQUEST']._serialized_end=145
  _globals['_READBYTESREPLY']._serialized_start=147
  _globals['_READBYTESREPLY']._serialized_end=178
  _globals['_KEYVALUESTORE']._serialized_start=181
  _globals['_KEYVALUESTORE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
