# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyvalue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekeyvalue.proto\x12\rkeyvaluestore\"-\n\x0fPutBytesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1c\n\rPutBytesReply\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0fGetBytesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\rGetBytesReply\x12\r\n\x05value\x18\x01 \x01(\x0c\x32\xa7\x01\n\rKeyValueStore\x12J\n\x08PutBytes\x12\x1e.keyvaluestore.PutBytesRequest\x1a\x1c.keyvaluestore.PutBytesReply\"\x00\x12J\n\x08GetBytes\x12\x1e.keyvaluestore.GetBytesRequest\x1a\x1c.keyvaluestore.GetBytesReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyvalue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUTBYTESREQUEST']._serialized_start=33
  _globals['_PUTBYTESREQUEST']._serialized_end=78
  _globals['_PUTBYTESREPLY']._serialized_start=80
  _globals['_PUTBYTESREPLY']._serialized_end=108
  _globals['_GETBYTESREQUEST']._serialized_start=110
  _globals['_GETBYTESREQUEST']._serialized_end=140
  _globals['_GETBYTESREPLY']._serialized_start=142
  _globals['_GETBYTESREPLY']._serialized_end=172
  _globals['_KEYVALUESTORE']._serialized_start=175
  _globals['_KEYVALUESTORE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
